#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NumericEditTextsample.Resource", IsApplication=true)]

namespace NumericEditTextsample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Akamud.Numericedittext.Resource.Attribute.maxDigitsAfterDecimal = global::NumericEditTextsample.Resource.Attribute.maxDigitsAfterDecimal;
			global::Akamud.Numericedittext.Resource.Attribute.maxDigitsBeforeDecimal = global::NumericEditTextsample.Resource.Attribute.maxDigitsBeforeDecimal;
			global::Akamud.Numericedittext.Resource.Attribute.overrideCurrencySymbol = global::NumericEditTextsample.Resource.Attribute.overrideCurrencySymbol;
			global::Akamud.Numericedittext.Resource.Attribute.showCurrencySymbol = global::NumericEditTextsample.Resource.Attribute.showCurrencySymbol;
			global::Akamud.Numericedittext.Resource.String.library_name = global::NumericEditTextsample.Resource.String.library_name;
			global::Akamud.Numericedittext.Resource.Styleable.NumericEditText = global::NumericEditTextsample.Resource.Styleable.NumericEditText;
			global::Akamud.Numericedittext.Resource.Styleable.NumericEditText_maxDigitsAfterDecimal = global::NumericEditTextsample.Resource.Styleable.NumericEditText_maxDigitsAfterDecimal;
			global::Akamud.Numericedittext.Resource.Styleable.NumericEditText_maxDigitsBeforeDecimal = global::NumericEditTextsample.Resource.Styleable.NumericEditText_maxDigitsBeforeDecimal;
			global::Akamud.Numericedittext.Resource.Styleable.NumericEditText_overrideCurrencySymbol = global::NumericEditTextsample.Resource.Styleable.NumericEditText_overrideCurrencySymbol;
			global::Akamud.Numericedittext.Resource.Styleable.NumericEditText_showCurrencySymbol = global::NumericEditTextsample.Resource.Styleable.NumericEditText_showCurrencySymbol;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int maxDigitsAfterDecimal = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int maxDigitsBeforeDecimal = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int overrideCurrencySymbol = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int showCurrencySymbol = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int myButton = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int myButton2 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int txtNumeric = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int txtNumericConstrained = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] NumericEditText = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int NumericEditText_maxDigitsAfterDecimal = 1;
			
			// aapt resource value: 0
			public const int NumericEditText_maxDigitsBeforeDecimal = 0;
			
			// aapt resource value: 3
			public const int NumericEditText_overrideCurrencySymbol = 3;
			
			// aapt resource value: 2
			public const int NumericEditText_showCurrencySymbol = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
